version: '3.8'

services:
  # 【Frontend】Nuxt.js
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    command: yarn dev
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    ports:
      - $FRONT_PORT:3000
    init: true
    restart: on-failure
